version: '3.3'
services:
  db:
    container_name: pastebin-db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: pastebin
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  phpfpm:
    container_name: pastebin-phpfpm
    build: ./php
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/pastebin
    depends_on:
      - db
  nginx:
    container_name: pastebin-nginx
    image: nginx:stable-alpine
    ports:
      - '5591:80'
    volumes:
      - ./app:/var/www/pastebin
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - phpfpm
      - db



